server:
  port: 5000

spring:
  application:
    name: Praxisruf Cloudservice
  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres

praxis-intercom:
  aws:
    accessKey: ${AWS_ACCESS_KEY}
    secretKey: ${AWS_SECRET_KEY}
    region: eu-west-1
    language: German
  fcm:
    credentials: ${FCM_CREDENTIALS}
  signaling:
    notification-type-for-unavailable: ${NOTIFICATION_TYPE_FOR_UNAVAILABLE}
  jwt:
    key: ${JWT_SECRET_KEY}
  api:
    admin-origin: ${ADMIN_ORIGIN}
