package ch.fhnw.ip6.praxisruf.commons.exception;

public enum ErrorCode {
    CALL_GROUP_ALREADY_EXISTS,
    CALL_GROUP_NOT_FOUND,
    CALL_TYPE_NOT_FOUND,
    CLIENT_NOT_FOUND,
    CLIENT_CONFIG_NOT_FOUND,
    CLIENT_CONFIG_ALREADY_EXISTS,
    CONNECTION_UNKNOWN,
    FCM_ERROR,
    INVALID_NOTIFICATION_TYPE,
    INVALID_REGISTRATION_INFORMATION,
    NOTIFICATION_NOT_FOUND,
    NOTIFICATION_TYPE_NOT_FOUND,
    NOTIFICATION_TYPE_ALREADY_EXISTS,
    USER_NOT_FOUND,
    REGISTRATION_NOT_FOUND,
    SPEECH_SYNTHESIS_ERROR
}
