server:
  servlet:
    context-path: "/praxis-intercom"
  port: 5000

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres

praxis-intercom:
  fcm:
    credentials: ${FCM_CREDENTIALS_PATH}
