spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/intercom_configuration_db_local
    username: admin
    password: secret

praxis-intercom:
  web:
    configurationClientUrl: "http://localhost:5000/praxis-intercom/api"
  api:
    admin-origin: "http://localhost:3000"
