server:
  servlet:
    context-path: "/praxis-intercom"
  port: 5000

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres

praxis-intercom:
  fcm:
    credentials:
      clientId: ${FCM_CLIENT_ID}
      clientEmail: ${FCM_CLIENT_EMAIL}
      privateKey: "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDEUHFdMBgq6jfl\nZrvE0HofxSw0pSITvgBVKPwshW/KGpwQi8qxeOvCES4Xo+0hzcw/4EC762SpcoKe\nXipeBIPIcXR/K7CwDPOHhB+P4qM+fgtSvw2NCUA1ahuupUlQqT7Xg6HRF9CZh3sR\ncAkncJaxk3EfGvMRg66TDxU1gAyjz+3J2aP4oGlSpgmjFAtRDghOlMj9k+rJEaB+\nAvZ1SpxP+fOjBVqrHPPFwvg+tFkQYX420pDRqN8J9N50Cepg0VXTB361YLHy8MGb\n+Uv0DbeL2WDolAOUZd5mxrJOk5E2Bk5HHnVR4y7+7Uk0Qs/f9e70mK+6LFHjrLe7\npOrqjL4pAgMBAAECggEAOj1NLGKwwMaEd6NvMBfTKyqxDxswTWAQNDN5AHJDtFcJ\nlqUKKHVhp8y1+mBw4JbvscGDItzWG6jzlC0Gb6byO5xg/btF6yykcL8jJ+oKGOeG\nz3ELgZxNdqs4dCrn4aycDo6oCmKAyZNWUNmGdbNimWLO6/XwR3Fj8I/IcHtBBLWM\n3mZZ9sZb22aZ9IpLWmHn7SNRoFB4YqLjyRKj4Qge/M/OX6fpyfCQNlUdl5E/Xd12\nqtayfp0UeYnTRr5YzAfo5TS5prFZ1t/BfdNQ+Z4wYQV2298wVrVrgHT+sxVM5vrJ\ny/Rfn4Mxplam/y+S28v+raIHgpXV3apEqijvkm+FEwKBgQD1PCT1K1TM8SAYUSj5\nfeQGoVixSLlw4pqnWIfGUVQuGfAIZOUSQHZ/fsPh+3cJka9eWvwXqlWr6keSYq1w\nzixZJQGrWJjvTJnDUyNbua/ZB/Jr4WZZ55gwNr+qcwANHB6WWCKT0JSyOBCNNJb6\nvALESfVQCBHAZzJongmzl8n9dwKBgQDM7ovhRq2PBQMfnrfe/BBmMXfO5cmUitac\n7M4AsokE0QR1cBCbtpLBG7tZpHyZRl6V9oklPhwMZd9+B3pN5I95G1Bpg4SHcPWc\nmOTOfQQaXqr571a9vIBwmbZyR3rk1D/Blp4jHjAF+hJJbzwLPSdLlsrwWOLR2m+Z\nk3758mWJXwKBgQDdGXe8r2+KQs+L/QhzQGRo8ek0FXxT4YpL3I61Z7f8xJfcCZNa\nDFKKCnFy+jRNpVK2QFPOxlztXZFf0qXK8aecS7ggkwV3otly+C8F0PlRNFAFobeU\n0TAuL/5IH9zo9PRC2n16RXD66X9KwCJrNz1LWd7ZZB0VGjWhivL2P6D2awKBgA/Q\n8VbHn6mEF4OfOk2pYpKgisCbF32xYXLnC9cd8FlA0HlH1uBNrPHedA0tFri1p6Mn\nTdpj+sIyMpeFeDj+xNvx8bjS/618WFhnrHELUP/AAq4bfLRUEg2er2gOgDuc7fbA\n6x+GuuobLMIiJZ4wcBHzZ2I5WfgcRbSyn4Am5xM9AoGBAOUxYxzrQYOHGJHyq+Rm\nsbKkAj4420n3uO7PwpdML19TidNboHO4jA1sgi0ds6Os8nAa1HBBDy/zydkMeBii\nB+znJDMLJbh23IpYrcwnrk+mQc5pN3m6ZVOSjTCP1A9IROZDCcrVi0J9IVsKwXVK\n/Hb6VRDsRl4gy6ymslcyNOOl\n-----END PRIVATE KEY-----\n"
      privateKeyId: ${FCM_PK_ID}
