server:
  port: 5000

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres

praxis-intercom:
  aws:
    accessKey: ${AWS_ACCESS_KEY}
    secretKey: ${AWS_SECRET_KEY}
  fcm:
    credentials: ${FCM_CREDENTIALS}
  jwt:
    key: ${JWT_SECRET_KEY}
  api:
    admin-origin: ${ADMIN_ORIGIN}
