package ch.fhnw.ip5.praxiscloudservice.api.exception;

public enum ErrorCode {
    USER_NOT_FOUND,
    CLIENT_NOT_FOUND,
    NOTIFICATION_NOT_FOUND,
    FCM_ERROR,
    INVALID_NOTIFICATION_TYPE,
    INVALID_REGISTRATION_INFORMATION,
    CLIENT_CONFIG_NOT_FOUND,
    CLIENT_CONFIG_ALREADY_EXISTS,
    NOTIFICATION_TYPE_NOT_FOUND,
    DUPLICATE_CONFIGURATION;
}
