server:
  servlet:
    context-path: "/praxis-intercom"
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keystore.p12
    key-store-password: password
    key-alias: tomcat

security:
  require-ssl: true
